name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for MySQL
      run: sleep 15  
    - name: Run tests
      run: |
        pytest
    - name: Print MySQL logs
      if: always()
      run: docker logs mysql
    - name: Check MySQL service status
      run: |
        echo "Checking MySQL service status..."
        mysqladmin -h 127.0.0.1 -P 3306 -u root -pexample status
    - name: Test MySQL connection
      run: |
        echo "Testing MySQL connection..."
        mysql -h 127.0.0.1 -P 3306 -u root -pexample -e "SHOW DATABASES;"